### ISSUE TITLE
toggle reset and descriptions

### ISSUE THREAD

**Issue by xinuxnt** [eschava/node-red-contrib-toggle#1]
Hello

Would be nice if it could have a "reset" input, I mean a way to set to off whenever it is on or off (I´m a noob and didn´t discover how to do that).  I´m using your node (by the way, Thank you!) and have several toggle nodes for switches, I want to make a "master reset" to push a button and turn off all that are "ON" without change all what it is "OFF"
Could that be possible?

**Comment by eschava** [comment]
I don't think that some code changes are needed for this
You just need another "change" node preparing "off" message for the node that should be connected to that "master reset" button and optionally you can use "if changed" pass-through mode if you don't want to send "off" message to the real switch if it's already switched off

**Comment by xinuxnt** [comment]
Oh, I understood! Thank you! I changed on/off topic and ON OFF payload and all work like I need! Whould be nice to have a littile description on readme.md to not to have to guess what do each item (almost for noobs ;-) like me)
