### ISSUE TITLE
Toggle switch functionality with boolean payload "true" as input

### ISSUE THREAD

**Issue by Vermatic** [eschava/node-red-contrib-toggle#4]
I have a button that outputs a boolean payload "true" every time it is pressed.

Now I wanted to use this node to get a toggle switch that alternates between boolean "true" and "false", but I failed.

I started with "Example 2: Basic toggle usage" but there is a catch.

I cannot leave the toggle value configured as "Any except ON/OFF", because obviously the toggle value is the same as the "on" value. But when I set it to boolean "true", it is the same as the "on" value and obviously won't toggle any more.
I now can set the on and off values to something different that boolean "true" and "false" - then the toggle functionality works, however the output then outputs these different values, which I also do not want.

So the question is: can I get the toggle switch functionality that works on the toggle input boolean "true" and outputs boolean "true" or "false"?

**Comment by eschava** [comment]
Can you put the "Change" node before the toggle switch to change your "true" output to something different?

**Comment by Vermatic** [comment]
Yes, then it works.

If I change the boolean payload "true" of my button with the change node to output the string "4711" instead (or anything that is not boolean "true") then it works as expected.

Of course the question is if this is a conceptual problem with the "toggle" node that makes it impossible to achieve what I want without the additional change node. 

If not, of course it would be nice to not be forced to use the additional change node.
If so, then adding this to the documentation would be beneficial.

**Comment by eschava** [comment]
I guess it's ok to use an additional node there instead of adding new configuration parameters to the toggle switch. I'll mention this in the docs
